name = "tiendamax"
main = "bot/cloudflare_worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "KV", id = "c7de12bdb92a4e23b24a44874a0702e7" }
]

[triggers]
crons = ["0 13 * * 1"]
